# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KoyApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoyApp

  target 'KoyAppTests' do
    inherit! :search_paths
    pod 'CircleMenu', '~> 1.0.0'
    pod 'Alamofire', '~> 3.4'
    # Pods for testing
  end

  target 'KoyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
